#!/usr/bin/env python3
"""
Debug the exact schema format being generated by the LLM
"""

import asyncio
import sys
import json
from pathlib import Path

# Add browser-use to path
sys.path.insert(0, str(Path(__file__).parent))

from runner import make_local_llm
from browser_use.llm.messages import SystemMessage, UserMessage

async def debug_llm_output():
    """Debug what the LLM is actually generating"""
    
    print("🔍 Debugging LLM output format...")
    
    try:
        llm = make_local_llm()
        
        # Test with the exact system prompt that browser-use would use
        system_prompt = """You are a web automation agent. You can navigate websites and interact with elements.

Available actions:
- click_element_by_index: Click on an element by its index
- input_text: Type text into an element
- done: Complete the task

You must respond with JSON in this exact format:
{
  "thinking": "your reasoning process",
  "evaluation_previous_goal": "assessment of previous step",
  "memory": "important information to remember",
  "next_goal": "what to do next",
  "action": [
    {
      "click_element_by_index": {
        "index": 1
      }
    }
  ]
}

The "action" field must be an array of action objects. Each action object has the action name as the key and parameters as the value.
"""
        
        user_prompt = """Current page: https://example.com
DOM elements:
[1] <h1>Example Domain</h1>
[2] <p>This domain is for use in illustrative examples...</p>

Task: Extract the main heading text.

Respond with the exact JSON format specified."""
        
        messages = [
            SystemMessage(content=system_prompt),
            UserMessage(content=user_prompt)
        ]
        
        print("Sending request...")
        result = await llm.ainvoke(messages)
        
        print(f"Raw response:")
        print("=" * 60)
        print(result.completion)
        print("=" * 60)
        
        # Try to parse and analyze the structure
        try:
            parsed = json.loads(result.completion)
            print("\n✅ Valid JSON structure:")
            print(f"Keys: {list(parsed.keys())}")
            
            if 'action' in parsed:
                print(f"'action' field type: {type(parsed['action'])}")
                print(f"'action' content: {parsed['action']}")
            
            if 'actions' in parsed:
                print(f"'actions' field type: {type(parsed['actions'])}")
                print(f"'actions' content: {parsed['actions']}")
                
            return parsed
            
        except json.JSONDecodeError as e:
            print(f"\n❌ Invalid JSON: {e}")
            return None
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return None

async def test_with_structured_output():
    """Test with browser-use structured output format"""
    
    print("\n" + "="*60)
    print("🔍 Testing with browser-use structured output...")
    
    try:
        from browser_use.agent.views import AgentOutput
        from browser_use.tools.registry.views import ActionModel
        
        # Get a simple action model for testing
        llm = make_local_llm()
        
        # Create a mock output format
        class TestAction(ActionModel):
            done: dict | None = None
            click_element_by_index: dict | None = None
        
        output_model = AgentOutput.type_with_custom_actions(TestAction)
        schema = output_model.model_json_schema()
        
        print("Expected schema:")
        print(json.dumps(schema, indent=2))
        
        # Test with structured output
        messages = [
            SystemMessage(content="You are a web automation agent. Respond with valid JSON matching the provided schema."),
            UserMessage(content="Task: Click on the main heading. Respond with JSON only.")
        ]
        
        print("\nSending structured output request...")
        result = await llm.ainvoke(messages, output_format=output_model)
        
        print(f"Structured result type: {type(result.completion)}")
        if hasattr(result.completion, 'model_dump'):
            print("Structured result:")
            print(json.dumps(result.completion.model_dump(), indent=2))
            return True
        else:
            print(f"Not structured: {result.completion}")
            return False
            
    except Exception as e:
        print(f"❌ Structured output error: {e}")
        import traceback
        traceback.print_exc()
        return False

async def main():
    print("🧪 SCHEMA FORMAT DEBUG")
    print("="*60)
    
    # Test 1: Raw output format
    raw_result = await debug_llm_output()
    
    # Test 2: Structured output
    structured_success = await test_with_structured_output()
    
    print("\n" + "="*60)
    print("🎯 DEBUG SUMMARY")
    print("="*60)
    
    if raw_result:
        print("✅ LLM generates valid JSON")
        if 'actions' in raw_result:
            print("⚠️ LLM uses 'actions' (plural) field")
        if 'action' in raw_result:
            print("✅ LLM uses 'action' (singular) field")
    else:
        print("❌ LLM does not generate valid JSON")
    
    print(f"Structured output: {'✅ PASS' if structured_success else '❌ FAIL'}")
    
    return structured_success

if __name__ == "__main__":
    success = asyncio.run(main())
    sys.exit(0 if success else 1)