#!/bin/bash
# llama.cpp server startup script for Browser-Use
# Generated by setup process

echo "Starting llama.cpp server with Moondream2..."
echo "Server will be available at http://localhost:8080"
echo "Press Ctrl+C to stop the server"

./llama.cpp/llama-server.exe \
    -m "./models/moondream2-text-model-f16.gguf" \
    --mmproj "./models/moondream2-mmproj-f16.gguf" \
    --host 0.0.0.0 \
    --port 8080 \
    --ctx-size 2048 \
    --threads 8 \
    --mlock \
    --log-format json \
    --verbose